### ISSUE TITLE
How can i get the full MQTT topic

### ISSUE THREAD

**Issue by marrobHD** [omersiar/esp-rfid#173]
I want to add this reader to Homeassistant but Homeassistant didnt detect the rfid chip.
```
- id: '1540281315142'
  alias: Marlons Zimmer Lock
  trigger:
  - payload: Marlon
    platform: mqtt
    topic: testrfid
  - payload: Adminchip
    platform: mqtt
    topic: testrfid
  condition: []
  action:
  - data:
      entity_id: switch.marlon_deckenlampe
    service: switch.toggle
```
