### ISSUE TITLE
How to reboot ESP-RFID via MQTT in Home Assistant?

### ISSUE THREAD

**Issue by DivanX10** [omersiar/esp-rfid#530]
I went through the topics and did not find an answer to my question, how to reboot ESP-RFID via MQTT in Home Assistant? I tried it and it didn't work out

* '{ "send":"restart"}'
* '{ "send":"restart", "doorip":"192.168.1.48"}'
* '{ "cmd":"restart"}'
* '{ "cmd":"restart", "doorip":"192.168.1.48"}'

```
service: mqtt.publish
data:
  topic: esprfid
  payload_template: '{ "cmd":"restart", "doorip":"192.168.1.48"}"
```

**Comment by IvanIzquierdoJimenez** [comment]
Hi, in the mqtt.esp no include restart how cmd command, yo need add this command on .esp file

**Comment by DivanX10** [comment]
> Hi, in the mqtt.esp no include restart how cmd command, yo need add this command on .esp file

Thanks, but I can't do it. If only the author can add to the firmware. I do not know how to add these commands to mqtt.esp and how to upload it to nodemcu later.

**Comment by IvanIzquierdoJimenez** [comment]
You need VScode and platformio to compile and modify the code, if you need something help, tell me

**Comment by DivanX10** [comment]
Yes, it would be great if you could show me what and how. For example, what code to add to the mnt.esp file and how to assemble it later, or I will be grateful for the finished firmware with the built-in command to reboot ESP-RFID

**Comment by IvanIzquierdoJimenez** [comment]
Yes, I will see how to make this, and tell you my progress.

**Comment by evazzoler** [comment]
IMHO it would be better if you put a home assistant relay in front of esp-rfid. That way you'll be sure to reboot esp-rfid even when/if it is totally frozen.

**Comment by DivanX10** [comment]
I express my gratitude to Aleks130699 for the working esp-rfid firmware. A similar topic was raised here [FIx Home Assistant integration ](https://github.com/esprfid/esp-rfid/pull/504 ). Now you can reboot the ESP board, there are sensors displaying the label. You can download the firmware from this [link](https://drive.google.com/drive/folders/15WgpG_04JhWDdBxhBjB9pIWSCzyGV4ll ). In the settings, you need to enable MQTT for Home Assistant, after which esp-rfid will appear in the Home Assistant.


![image](https://user-images.githubusercontent.com/64090632/200135114-fc45037d-2518-45f3-8aff-e4ca433b9d66.png)
![image](https://user-images.githubusercontent.com/64090632/200135068-acbe81c3-5878-4b78-b29b-08ba2d24f8e8.png)
![image](https://user-images.githubusercontent.com/64090632/200135360-e4526f20-308e-4c4d-b6f1-586bf30c0912.png)


Thanks to this, I now have an excellent reading from the label. More details about my project can be found [here](https://youtu.be/71JAbj5qM5I ). Where I have embedded tags in air freshener cylinders in a smart air freshener and when changing the cylinder, the Home Assistant understands which cylinder is installed and takes into account the resource of the cylinder consumption

**Comment by DivanX10** [comment]
> IMHO it would be better if you put a home assistant relay in front of esp-rfid. That way you'll be sure to reboot esp-rfid even when/if it is totally frozen.

Now this is not required, you can just download the firmware from this [link](https://drive.google.com/drive/folders/15WgpG_04JhWDdBxhBjB9pIWSCzyGV4ll) and esp-rfid will appear in the Home Assistant

**Comment by DivanX10** [comment]
A working reboot command via the MQTT service for this [firmware](https://drive.google.com/drive/folders/15WgpG_04JhWDdBxhBjB9pIWSCzyGV4ll)

```
service: mqtt.publish
data:
  topic: esprfid/cmd
  payload: "{cmd:'reboot',doorip:'192.168.1.48'}"
```

**Comment by evazzoler** [comment]
I still don't understand the usefulness of restarting a working and responding device.
Please, erudite me!

**Comment by matjack1** [comment]
@DivanX10 let us know what's your use case for this as I agree with @evazzoler, I cannot understand the purpose. Seems like we are trying to bypass fixing an error that you are experiencing? Would be nice to solve the root cause of the issue, rather than rebooting it to hide the problem.

**Comment by DivanX10** [comment]
> I still don't understand the usefulness of restarting a working and responding device. Please, erudite me!

I have a smart air freshener that works according to the Zigbee protocol and on batteries, and I am also in the process of creating a base for an air freshener, which will have a built-in MC RC522, wemos mini reader module and power is supplied to charge batteries in it, similar to a radiotelephone that stands at a telephone exchange. This air freshener refreshes the air in the toilet through both Voice Assistant and Home Assistant automation. For a variety of flavors, I often change the cylinders, I can change them two or three times a week, or I can change them once a week, but the flavors change often. In order to know the consumption resource of the balloon flavors and when the balloon resource is coming to an end, the Home Assistant will inform me in advance that it's time to buy a new balloon. You can know which is the most frequent fragrance used. Further, the selected fragrance is automatically set in the Home Assistant according to the read label and continues accounting for this balloon further. When you change the balloon, the MC RC522 tag reader does not respond to the tag, either falls asleep, or freezes and only a reboot helps. After restarting, the balloon is read and the voice assistant informs that the balloon is installed and informs which flavor is selected. I added a reboot to the automation when I take the balloon out of the air freshener and after that the reader reads the label 100% and there is no such situation that after installing the balloon in the air freshener, the automation does not work out to the end, because the reader does not respond to the label and I had to reboot the board by de-energizing

<details>
  <summary>Photos of the Zigbee smart air freshener and a 3D model of the future base</summary>
  
![image](https://user-images.githubusercontent.com/64090632/200413763-823c791e-cc63-41a8-8ee4-2ce45f79deef.png)
![image](https://user-images.githubusercontent.com/64090632/200416652-1617ab4f-718c-4ec0-9acc-6d06ebdfde4f.png)
![image](https://user-images.githubusercontent.com/64090632/200417156-ffa2476b-f617-4aa3-b3ac-b0168c33c2a4.png)
![image](https://user-images.githubusercontent.com/64090632/200413895-4452c371-8ce5-4e89-b9fd-96caba26225c.png)
![image](https://user-images.githubusercontent.com/64090632/200413942-da861920-223a-4028-9a59-a4e7d957eda9.png)
![image](https://user-images.githubusercontent.com/64090632/200413854-07eaa06c-6641-4bd9-87e3-e30f0aa55caf.png)
![image](https://user-images.githubusercontent.com/64090632/200421075-cdb6872c-e295-4c30-b69b-4925b9df45f2.png)
![image](https://user-images.githubusercontent.com/64090632/200414083-b3646982-16f8-4591-9984-f2c160d324a9.png)
![image](https://user-images.githubusercontent.com/64090632/200414110-64176893-a006-4058-a457-694fdf2b0293.png)
  
</details>


<details>
  <summary>Example of automation Toilet: Air freshener. Counter. Cylinder resource</summary>
  
```
alias: "Toilet: Air freshener. Counter. Cylinder resource"
description: >-
  With each spray, a counter will be triggered and, depending on the selected
  cylinder, the calculation will be carried out for the selected cylinder. If the cylinder is
  removed, the general counter is reset, and the cylinder counters are reset
  strictly manually. If you select the desired cylinder from the drop-down list, the
  number of sprays will be restored, provided that the counter of the selected
  cylinder has not been reset manually
trigger:
  - platform: state
    entity_id:
      - sensor.tualet_osvezhitel_vozdukha_action
    attribute: state_l1
    id: Pressing the button
    alias: Pressing the button
  - platform: state
    entity_id:
      - input_select.air_freshener_replaceable_balloons
    id: The balloon is selected
    alias: The balloon is selected
  - platform: state
    entity_id:
      - input_select.air_freshener_replaceable_balloons
      - sensor.toilet_air_freshener_status
    to: The balloon is removed
    id: The balloon is removed
    alias: The balloon is removed
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: Pressing the button
            alias: Pressing the button
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ not is state('input_select.air_freshener_replaceable_balloons', 'balloon is removed') }}
                  - condition: template
                    value_template: >-
                      {{ not is_state('sensor.toilet_air_freshener_status','balloon is removed') }}
                sequence:
                  - service: counter.increment
                    data: {}
                    target:
                      entity_id: counter.toilet_air_freshener_spray_counter
                  - service: counter.increment
                    data: {}
                    target:
                      entity_id: >
                        {% set ballon_installed = states('input_select.air_freshener_replaceable_balloons')%}
			{% if ballon_installed == 'Ocean Oasis' %} counter.balloon_aroma_ocean_oasis
			{% elif ballon_installed == 'Peony and juicy berries' %} counter.balloon_aroma_peony_and_juicy_berries
			{% elif ballon_installed == 'Freshness of linen' %} counter.balloon_aroma_freshness_of_linen
			{% elif ballon_installed == 'Freshness of the morning' %} counter.balloon_aroma_freshness_of_the_morning
			{% elif ballon_installed == 'Japanese Garden' %} counter.balloon_aroma_japanese_garden 
			{% endif %}
            default: []
      - conditions:
          - condition: trigger
            id: The balloon is removed
            alias: The balloon is removed
        sequence:
          - service: counter.reset
            data: {}
            target:
              entity_id: counter.toilet_air_freshener_spray_counter
            alias: "Reset the toilet counter: Air freshener. Counter"
          - service: input_select.select_option
            data:
              option: The balloon is removed
            target:
              entity_id:
                - input_select.air_freshener_replaceable_balloons
            alias: "List: The balloon has been removed"
          - service: mqtt.publish
            data:
              topic: esprfid/cmd
              payload: "{cmd:'reboot',doorip:'192.168.1.48'}"
            alias: Restart ESP RFID
      - conditions:
          - condition: trigger
            id: The balloon is selected
            alias: The balloon is selected
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ is_state('sensor.toilet_air_freshener_status','The balloon is removed') }}
                    alias: "Air freshener: The cylinder is removed"
                sequence:
                  - delay:
                      hours: 0
                      minutes: 0
                      seconds: 5
                      milliseconds: 0
                    alias: Delay of 5 seconds
                  - service: input_select.select_option
                    data:
                      option: The balloon is removed
                    target:
                      entity_id: input_select.air_freshener_replaceable_balloons
                    alias: "List: The balloon has been removed"
              - conditions:
                  - condition: template
                    value_template: >-
                      {{
                      is_state('sensor.toilet_air_freshener_status','Works')
                      }}
                    alias: "Air Freshener: Works"
                sequence:
                  - service: counter.configure
                    data:
                      value: >
                        {% set ballon_installed = states('input_select.air_freshener_replaceable_balloons') %}
			{% if ballon_installed == 'The balloon is removed' %} 0
			{% elif ballon_installed == 'Ocean Oasis' %}
			{{ states('counter.balloon_aroma_ocean_oasis') }}
			{% elif ballon_installed == 'Peony and juicy berries' %}
			{{ states('counter.balloon_aroma_peony_and_juicy_berries') }}
			{% elif ballon_installed == 'Freshness of linen' %}
			{{ states('counter.balloon_aroma_freshness_of_linen') }}
			{% elif ballon_installed == 'Freshness of the morning' %}
			{{ states('counter.balloon_aroma_freshness_of_the_morning') }}
			{% elif ballon_installed == 'Japanese Garden' %}
			{{ states('counter.balloon_aroma_japanese_garden') }}
			{% endif %}
                    target:
                      entity_id: counter.toilet_air_freshener_spray_counter
            default: []
    default: []
mode: restart

```
</details>
